name: build and test

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        # see https://github.com/actions/virtual-environments/
        os:
          - ubuntu-latest
          - macos-latest
        swift:
          - "5.2"
          - "5.3"
          - "5.4"
          - "5.5"
        exclude:
          - os: ubuntu-latest
            swift: "5.5"
          - os: macos-latest
            swift: "5.2"
          - os: macos-latest
            swift: "5.5"
    runs-on: ${{ matrix.os }}
    steps:
        # see https://github.com/fwal/setup-swift
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Show swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
